apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-test-pod
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "wallet-role"
    vault.hashicorp.com/agent-inject-secret-wallet-db: "secret/data/finedge/wallet"
    # This template formats the raw JSON into a sourceable environment file
    vault.hashicorp.com/agent-inject-template-wallet-db: |
      {{- with secret "secret/data/finedge/wallet" -}}
      export MONGODB_URI="{{ .Data.data.mongodb_uri }}"
      {{- end -}}
spec:
  serviceAccountName: wallet-sa
  containers:
    - name: app
      image: alpine:latest
      command: ["/bin/sh", "-c", "sleep 3600"]